esphome:
  name: ac-switch

esp8266:
  board: d1_mini

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""

wifi:
  ssid: !secret home_ssid
  password: !secret home_password

  # # Enable fallback hotspot (captive portal) in case wifi connection fails
  # ap:
  #   ssid: "Ac Switch Fallback Hotspot"
  #   password: "s552iruw61rX"

captive_portal:
    
remote_transmitter:
  pin: D1
  carrier_duty_percent: 50%

sensor:
  - platform: dht
    pin: D2
    temperature:
      name: AC Temp
    humidity:
      name: AC Humidity
    update_interval: 5s

climate:
  - platform: mitsubishi
    name: Living Room AC
    sensor: AC Temp
    min_heating_off_time: 300s
    min_heating_run_time: 300s
    min_idle_time: 30s
    heat_action:
      - switch.turn_on: heater
    idle_action:
      - switch.turn_off: heater
    default_preset: Home
    preset:
      - name: Home
        default_target_temperature_low: 20 °C
    visual:
      min_temperature: 18
      max_temperature: 25
      temperature_step: 1


web_server:
  port: 80