esphome:
  name: ac-switch

esp8266:
  board: d1_mini

# Enable logging
logger:
  level: INFO

# Enable Home Assistant API
api:
  password: ""

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

captive_portal:
    
remote_transmitter:
  pin: D1
  carrier_duty_percent: 50%

sensor:
  - platform: dht
    pin: D2
    temperature:
      id: ac_temp
      name: ac_temp
    humidity:
      id: ac_humidity
      name: ac_humidity
    update_interval: 5s

# Sync time with Home Assistant.
time:
  - platform: homeassistant
    id: homeassistant_time

climate:
  - platform: mitsubishi
    name: living_room_ac
    sensor: ac_temp
    # supports:
    #   mode: ['HEAT_COOL', 'COOL', 'HEAT', 'DRY', 'FAN_ONLY']
    #   fan_mode: [AUTO, LOW, MEDIUM, HIGH]
    #   swing_mode: [OFF, VERTICAL, HORIZONTAL]
    visual:
      min_temperature: 18
      max_temperature: 25
      temperature_step: 1


web_server:
  port: 80